# File: src/video/config/usb_cam_params.yaml

/camera_driver:
    ros__parameters:
        video_device: "/dev/video0"
        framerate: 30.0
        image_width: 640
        image_height: 480
        pixel_format: "uyvy2rgb"
        frame_id: "camera_optical_frame"
        brightness: 128
        # auto_white_balance: true