# File: src/video/config/video_quat_config.yaml

/video_quat:
    ros__parameters:
        loc_type: 'apriltag' # can be 'apriltag' or 'sift'
        save_path: '/home/introlab/multimodal_recorder/data/raw/multimodal/session_test_20/video/'
        save_video: False
