# File: src/video/config/video_quat_config.yaml

/video_quat:
    ros__parameters:
        model: 'yolo' # pose estimation model 'apriltag' or 'yolo' or ...
        save_path: '/home/introlab/multimodal_recorder/data/raw/multimodal/calibration_test/video/'
        
        # Processing parameters
        processing_enabled: False
        processing_fps: 1 