# File: src/fuse/config/fuse_config.yaml

/fuse:
    ros__parameters:
        # IMU SCALING CALIBRATION PARAMETERS
        imu_scale_pitch: 1.076
        imu_scale_yaw: 1.007
        imu_scale_roll: 1.000

