# File: src/imu/config/imu_adq_config.yaml

/audio_adq:
    ros__parameters:
        operation_mode: 'rt' # can be 'csv' or 'rt'
        csv_path: '/home/introlab/multimodal_recorder/data/raw/multimodal/session_test_for_ros/audio/audio_timestamps.csv'
        audio_path: '/home/introlab/multimodal_recorder/data/raw/multimodal/session_test_for_ros/audio/audio.wav'
        device: 'hw:1,0'
        samplerate: 16000
        channels: 16
        blocksize: 4096
        sampwidth: 4

